spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
 spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bluepal_ecomm?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
 port: 8081

# Application messages goes here
auth-service:
 messages: 
  userReg: User Created
  userRegErr: User Creation Failed
  login: Login Success
  loginErr: Invalid Credentials  
